### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by DQ318** [Maseya/SnesXM#1]
Hello! I'm trying to compile the project, however, I'm getting the following errors:

1> ------ Compilation started: Project: SnesXM, Configuration: Debug Any CPU ------
C: \ Program Files \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ 15.0 \ Bin \ Microsoft.Common.CurrentVersion.targets (1128,5): warning MSB3191: Unable to create directory "C: \ Users \ nrgarcia \ Dropbox \ Private \ Programming \ GitHub \ SnesXM \ src \ SnesXM \ SnesXM \ ". Access to the path 'C: \ Users \ nrgarcia \ Dropbox \ Private \ Programming \ GitHub \ SnesXM \ src \ SnesXM \ SnesXM \' was denied.
1> CSC: error CS0016: Unable to write to output file "C: \ Users \ nrgarcia \ Dropbox \ Private \ Programming \ GnsubM \ SnesXM \ src \ SnesXM \ SnesXM \ SnesXM.xml" - "Could not find a part of the path 'C: \ Users \ nrgarcia \ Dropbox \ Private \ Programming \ GnesHub \ SnesXM \ src \ SnesXM \ SnesXM \ SnesXM.xml'. "
1> Ready build project "SnesXM.csproj" - FAIL.
========== Compile: 0 Successfully, 1 Failed, 0 Updated, 0 Ignored ==========

**Comment by bonimy** [comment]
The problem was the XML documentation file was trying to write to a hardcoded path that you did not have access to. I resolved this issue in 18564960025d88e3842208ec95f019564032514c and I merged the commit into all other branches.

Just so you are aware, this is nowhere near a functioning emulator yet. I've only barely written unit tests for some math functions. If however you are hear to help make contributions, then welcome aboard.
